sonar.projectKey=luisbarcia_n8n-nodes-brasil-hub
sonar.organization=luisbarcia

sonar.sources=nodes/
sonar.tests=__tests__
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=node_modules/**,dist/**,coverage/**,__mocks__/**
sonar.typescript.lcov.reportPaths=coverage/lcov.info
